# CMake generated Testfile for 
# Source directory: C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb
# Build directory: C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(leveldb_tests "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Debug/leveldb_tests.exe")
  set_tests_properties(leveldb_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;365;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(leveldb_tests "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Release/leveldb_tests.exe")
  set_tests_properties(leveldb_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;365;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(leveldb_tests "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/MinSizeRel/leveldb_tests.exe")
  set_tests_properties(leveldb_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;365;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(leveldb_tests "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/RelWithDebInfo/leveldb_tests.exe")
  set_tests_properties(leveldb_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;365;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
else()
  add_test(leveldb_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Debug/c_test.exe")
  set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;394;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Release/c_test.exe")
  set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;394;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/MinSizeRel/c_test.exe")
  set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;394;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/RelWithDebInfo/c_test.exe")
  set_tests_properties(c_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;394;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
else()
  add_test(c_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(env_windows_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Debug/env_windows_test.exe")
  set_tests_properties(env_windows_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;400;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(env_windows_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/Release/env_windows_test.exe")
  set_tests_properties(env_windows_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;400;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(env_windows_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/MinSizeRel/env_windows_test.exe")
  set_tests_properties(env_windows_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;400;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(env_windows_test "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/RelWithDebInfo/env_windows_test.exe")
  set_tests_properties(env_windows_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;391;add_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;400;leveldb_test;C:/Users/Jabir/WebstormProjects/Voting/merkletreeids/leveldb/CMakeLists.txt;0;")
else()
  add_test(env_windows_test NOT_AVAILABLE)
endif()
subdirs("third_party/googletest")
subdirs("third_party/benchmark")
